### ISSUE TITLE
I don't know the environment that Pegasus compiles depends on

### ISSUE THREAD

**Issue by Smityz** [apache/incubator-pegasus#635]
I can't  access to https://pegasus.apache.org/docs/installation/ to get the dependency version requirements
BTW, according to [document history version](https://github.com/pegasus-kv/pegasus-kv.github.io/commit/2f89a06b3eec82140b7b9ffbc4b7b2f332c31f30#diff-bdaaeb844c24423ef50a25e96b33974c405c21b5ec9fb0bca4d00bab4fe2b063), the minimum requirements of cmake is 3.5.2, but it is too old to extract tarball filename from url, I suggest to update it.

**Comment by neverchanje** [comment]
Links were changed. http://pegasus.apache.org/docs/build/compile-from-source/. We have no guarantee for keeping the url unchanged. You should find the doc from the sidebar in http://pegasus.apache.org/docs. Or just search using the searchbar on top of each page.

**Comment by Smityz** [comment]
I still can't find the requirements of GCC/CMake/boost

**Comment by neverchanje** [comment]
Ok. I've updated the requirements of gcc & cmake on the doc, please check it out.
There's no requirement to install boost via `apt-get/yum` since we manage it through cmake ExternalProject. https://github.com/XiaoMi/rdsn/blob/master/thirdparty/CMakeLists.txt#L29. You don't need to install it yourself.
