### ISSUE TITLE
support jemalloc

### ISSUE THREAD

**Issue by levy5307** [apache/incubator-pegasus#819]
## Feature Request

make pegasus to support jemalloc

### Related pull requests

https://github.com/XiaoMi/rdsn/pull/910

**Comment by empiredan** [comment]
## Support to set/get dirty_decay_ms and muzzy_decay_ms dynamically

Since we've supported building rDSN with jemalloc in https://github.com/XiaoMi/rdsn/pull/910, it's necessary for us to  supporting setting/getting dirty_decay_ms and muzzy_decay_ms dynamically. 

For details please see https://github.com/XiaoMi/rdsn/pull/928
